services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=laboratory'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=administator723'
    ports:
      - '5432:5432'
